name: GitHub Actions Fire Blog
run-name: ${{ github.actor }} is flying to the moon with GitHub Actions ðŸš€
on: [push]
jobs:
  init:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Starting Node.js 18
        uses: actions/setup-node@v3
        with:
          node-version: 18
      - name: install modules
        run: npm install
      - name: lint fix
        run: npm run lint:fix
      - name: lint code check
        run: npm run lint
      - name: build project
        run: npm run build
